# -*- coding: utf-8 -*-
"""statistics_and_trends

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKZrbrSVTrj15EfwJaRZIzZq8CJKlqIl
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("data.csv")

print(df.head())

print(df.shape)

print(df.columns)

print(df.isnull().sum())

print(df.describe(include='all'))

# RELATIONAL PLOT

plt.figure(figsize=(14, 7))

sns.set_style("whitegrid")

sns.scatterplot(
    data=df.sample(1500),
    x='release_year',
    y='rating',
    hue='type',
    palette='viridis',
    s=90,
    alpha=0.8
)
plt.title("Netflix Content Ratings by Release Year")

plt.xlabel("Release Year")

plt.ylabel("Rating Category")

plt.legend(title='Content Type')

plt.tight_layout()

plt.show()

# CATEGORICAL GRAPH

plt.figure(figsize=(14, 7))

sns.set_style("whitegrid")

sns.countplot(
    data=df,
    x='rating',
    hue='type',
    palette='magma'

)

plt.title(
    "Distribution of Netflix Ratings by Content Type",
    fontsize=18,
    fontweight='bold'
)

plt.xlabel("Rating Category", fontsize=13)

plt.ylabel("Number of Shows", fontsize=13)

plt.xticks(rotation=45, fontsize=10)

plt.yticks(fontsize=10)

plt.legend(title='Content Type', fontsize=10, title_fontsize=11)

plt.grid(axis='y', linestyle='--', alpha=0.4)

plt.tight_layout()

plt.show()

# STATISTICAL GRAPH

plt.figure(figsize=(14, 7))

sns.set_style("whitegrid")

sns.histplot(
    data=df,
    x='release_year',
    bins=30,
    kde=True,
    color='purple'
)
plt.title(
    "Distribution of Netflix Release Years", 
    fontsize=20, 
    fontweight='bold'
)

plt.xlabel("Release Year", fontsize=14)

plt.ylabel("Frequency", fontsize=14)

plt.xticks(fontsize=11)

plt.yticks(fontsize=11)

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()

plt.show()

# USE OF STATISTICS

print("Mean Release Year:")
print(df['release_year'].mean())

print("\nMedian Release Year:")
print(df['release_year'].median())

print("\nMode of Ratings:")
print(df['rating'].mode())

print("\nStandard Deviation:")
print(df['release_year'].std())

print("\nSummary Statistics:")
print(df['release_year'].describe())

"""Conclusion:

1. Netflix content increased rapidly after 2010.
2. TV-MA is the most common rating category.
3. Most content on Netflix was released between 2015 and 2021.
4. Movies are more common than TV Shows in the dataset.
5. Statistical analysis shows strong growth in modern streaming content.
"""
